'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued
terms.'''

i = 3
sum=0
while True:
    t = ((((1+(5**0.5))/2)**i)-(((1-(5**0.5))/2)**i))/(5**0.5)
    if t < 4000000:
        sum += t
        i+=3
    else:
        break
print(sum)
# 4613732.000000005 Just approx lol